server.port: 80

solon:
  app:
    name: stock
  logging.appender.console.level: INFO

wood:
  db:
    jdbcUrl: ${JDBC_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    minIdle: 1

mairui.licence: ${MAIRUI_LICENCE}